# Day 13 — Practice Session · **SOLUTIONS**
### Broadcasting & Vectorised Operations · Python for Data Science

**Prepared by Srinivasa Sai Chava**  ·  Boston University

---

> **Instructor copy.** Every question is followed by the answer and the reasoning.
> The student copy (`Day13_Practice_Questions.ipynb`) is identical minus the answer blocks.

| Part | Focus | Questions |
|---|---|---|
| A | Predict the output | 8 |
| B | Spot & fix the bug | 4 |
| C | Write the code | 5 |
| D | Challenge | 2 |

---
## Setup — run this first

In [ ]:
import numpy as np
np.random.seed(42)
print('ready')

---
## Setup — run this first

In [ ]:
import numpy as np
np.random.seed(42)
print('ready')

---
# Part A — Predict the Output  *(8 min)*

---
# Part A — Predict the Output

**Teaching note:** A4 is the one that decides whether they understood the rule. A7 (argmax
returning a position) and A8 (ddof) are the two most often guessed wrong.

### A1. What is printed?

In [ ]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
print(a * b)
print(a @ b)

*Your prediction:*  

> ### ✅ Answer A1
> ```
> [10 40 90]
> 140
> ```
> **Why:** `*` multiplies **matching positions** — 1×10, 2×20, 3×30. `@` is the dot
> product: it multiplies and then **sums**, giving 10 + 40 + 90 = 140.
>
> Reaching for `*` when you meant a dot product gives no error, just the wrong answer in the
> wrong shape. You will need `@` properly in Module 4.

### A2. Which of these work?

In [ ]:
a = np.ones((3, 4))
print((a + np.ones(4)).shape)
print((a + np.ones((3, 1))).shape)
print((a + np.ones(3)).shape)

*Your prediction:*  

> ### ✅ Answer A2
> ```
> (3, 4)
> (3, 4)
> ValueError: operands could not be broadcast together with shapes (3,4) (3,)
> ```
> **Why — align from the right each time:**
>
> ```
>   (3, 4)        (3, 4)        (3, 4)
>      (4,)       (3, 1)           (3,)
>   4 vs 4 ✓      4 vs 1 ✓        4 vs 3 ✗
>                 3 vs 3 ✓
> ```
> The third fails because 4 and 3 are neither equal nor 1. A bare `(3,)` lines up against
> the **last** axis, which has length 4.

### A3. What shape comes out?

In [ ]:
v = np.arange(3)
print((v + v).shape)
print((v[:, None] + v).shape)

*Your prediction:*  

> ### ✅ Answer A3
> ```
> (3,)
> (3, 3)
> ```
> **Why:** `v + v` is `(3,) + (3,)` — same shape, plain element-wise, still `(3,)`.
>
> `v[:, None]` is `(3, 1)`. Aligning `(3, 1)` against `(3,)`:
> ```
>   (3, 1)
>      (3,)
>   1 vs 3 -> stretch to 3
>   3 vs (missing) -> padded to 1, stretch to 3
> ```
> Both get stretched, producing a **3×3 grid**. This is how you build a multiplication
> table with no loops — it is today's homework.

### A4. What is printed?

In [ ]:
m = np.array([[1, 2, 3],
              [4, 5, 6]])
print(m.sum(axis=0))
print(m.sum(axis=1))
print(m.sum(axis=0).shape)

*Your prediction:*  

> ### ✅ Answer A4
> ```
> [5 7 9]
> [ 6 15]
> (3,)
> ```
> **Why:** `axis=0` collapses **down** the rows, so 1+4, 2+5, 3+6 — one value per column.
> `axis=1` collapses **across** the columns: 1+2+3 and 4+5+6.
>
> **The reliable rule:** the axis you name is the one that **disappears from the shape**.
> `(2, 3)` with `axis=0` leaves `(3,)`. Forget "rows" and "columns" and just watch the shape.

### A5. What does the mask produce?

In [ ]:
marks = np.array([88, 35, 71, 22, 64])
print(np.where(marks >= 40, "pass", "fail"))
print(np.clip(marks, 40, 80))

*Your prediction:*  

> ### ✅ Answer A5
> ```
> ['pass' 'fail' 'pass' 'fail' 'pass']
> [80 40 71 40 64]
> ```
> **Why:** `np.where(condition, if_true, if_false)` is Day 6's `A if cond else B` applied to
> every element — nothing is dropped, so the result is always the same length.
>
> `clip(40, 80)` pulls everything into that range: 88 comes down to 80, 35 and 22 come up to
> 40, and 71 and 64 were already inside. Useful for capping outliers, which is Day 20.

### A6. True or False for each?

In [ ]:
marks = np.array([88, 35, 71, 22, 64])
print((marks > 90).any())
print((marks > 20).all())
print((marks < 40).sum())

*Your prediction:*  

> ### ✅ Answer A6
> ```
> False
> True
> 2
> ```
> **Why:** the highest mark is 88, so nothing is above 90. The lowest is 22, so everything
> is above 20. Two marks (35 and 22) are below 40, and `.sum()` counts them because
> **`True` counts as 1** — Day 1.
>
> `any()` and `all()` are what you put inside an `if`. A raw mask cannot go there — that is
> what yesterday's *"truth value of an array is ambiguous"* error was telling you.

### A7. What does this print?

In [ ]:
arr = np.array([10, 50, 30, 20])
print(arr.argmax())
print(arr.max())

*Your prediction:*  

> ### ✅ Answer A7
> ```
> 1
> 50
> ```
> **Why:** `argmax` returns the **position** of the largest value, not the value itself. The
> largest is 50, which sits at index 1.
>
> The pair is often used together: `arr[arr.argmax()]` gives the value, and `argmax` alone
> tells you *which* row or student it belonged to — usually the more useful answer.
>
> On a 2-D array, `argmax()` with no axis flattens first, so it returns a position in the
> flattened array.

### A8. Are these the same?

In [ ]:
arr = np.array([1., 2., 3., 4.])
print(arr.std())
print(arr.std(ddof=1))

*Your prediction:*  

> ### ✅ Answer A8
> ```
> 1.118033988749895
> 1.2909944487358056
> ```
> **Why:** they are different. `std()` defaults to `ddof=0` — the **population** formula,
> dividing by *n*. `ddof=1` divides by *n − 1*, the **sample** formula.
>
> **Worth remembering now:** NumPy defaults to population, pandas defaults to sample. If a
> standard deviation ever disagrees between the two, this is why. Module 2 covers the
> statistical reasoning.

---
# Part B — Spot & Fix the Bug  *(7 min)*

---
# Part B — Spot & Fix the Bug

**Teaching note:** B1 is the error they will hit most this week. B4 is the dangerous one —
no error, just a wrong number.

### B1. This should subtract each student's average from their marks.

In [ ]:
marks = np.array([[88, 71, 64],
                  [45, 38, 52],
                  [91, 84, 79]])

student_avg = marks.mean(axis=1)      # one per student
print(marks - student_avg)

*Error:* 

*Your fix:*

> ### ✅ Answer B1
> **There is no error — and that is the problem.** The code runs and prints a plausible
> 3×3 array of wrong numbers.
>
> **Cause:** `student_avg` is `(3,)`, which aligns with the **last** axis — the columns. So
> NumPy subtracted student 0's average from *column* 0 of every row, student 1's average
> from column 1, and so on. The averages were applied across the wrong axis entirely.
>
> The array being **square** is what hides it. With 3 students and 4 subjects the same
> mistake would raise `ValueError` immediately — which is far kinder.

In [ ]:
marks = np.array([[88, 71, 64],
                  [45, 38, 52],
                  [91, 84, 79]])
student_avg = marks.mean(axis=1)

print("marks.shape      :", marks.shape)        # (3, 3)
print("student_avg.shape:", student_avg.shape)  # (3,)

# A (3,) lines up against the LAST axis - the COLUMNS.
print("\nWRONG (averages applied down the columns):")
print((marks - student_avg).round(1))

# THE FIX: make it a column so it lines up with the ROWS
print("\nCORRECT (each student minus their own average):")
print((marks - student_avg.reshape(-1, 1)).round(1))

# Proof the fix is right: every row now sums to zero.
print("\nrow sums after the fix:",
      (marks - student_avg.reshape(-1, 1)).sum(axis=1).round(10))

# And here is the same mistake on a NON-square array, where it errors loudly:
wide = np.array([[88., 71., 64., 90.],
                 [45., 38., 52., 40.],
                 [91., 84., 79., 88.]])
try:
    wide - wide.mean(axis=1)
except ValueError as e:
    print("\n3x4 version ->", str(e)[:58])

### B2. This should give the dot product.

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a * b)

*What's wrong:* 

*Your fix:*

> ### ✅ Answer B2
> **Symptom:** prints `[ 4 10 18]` — an array, when a dot product should be a single number.
> **Cause:** `*` is element-wise. There is no error, just the wrong kind of answer.

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("element-wise  :", a * b)        # [ 4 10 18]
print("dot product   :", a @ b)        # 32
print("same thing    :", (a * b).sum())  # 32 - what @ does internally

# @ multiplies matching positions and then SUMS.
# np.dot(a, b) is the older spelling of the same thing.

### B3. This should report whether anyone failed.

In [ ]:
marks = np.array([88, 35, 71, 22, 64])

if marks < 40:
    print("someone failed")

*Error:* 

*Your fix:*

> ### ✅ Answer B3
> **Error:** `ValueError: The truth value of an array with more than one element is ambiguous`
> **Cause:** `marks < 40` is an array of five booleans. `if` needs a single `True` or
> `False`, and NumPy refuses to guess whether you meant "any" or "all".

In [ ]:
marks = np.array([88, 35, 71, 22, 64])

if (marks < 40).any():
    print("someone failed:", marks[marks < 40])

if (marks >= 40).all():
    print("everyone passed")
else:
    print("not everyone passed")

print("how many failed:", (marks < 40).sum())

# any()  -> is at least one True?
# all()  -> are they all True?
# sum()  -> how many are True?

### B4. This should give the sample standard deviation and the top mark.

In [ ]:
marks = np.array([88., 35., 71., 22., 64.])

print("std      :", marks.std())
print("top mark :", marks.argmax())

*What's wrong:* 

*Your fix:*

> ### ✅ Answer B4
> **Two bugs, neither of which raises an error.**
> 1. `std()` uses `ddof=0`, the **population** formula. The sample formula needs `ddof=1`.
> 2. `argmax()` returns the **position** (0), not the mark (88).
>
> Both produce plausible-looking numbers, which is exactly what makes them dangerous.

In [ ]:
marks = np.array([88., 35., 71., 22., 64.])

print("population std :", marks.std().round(4))
print("sample std     :", marks.std(ddof=1).round(4))
print()
print("position of top:", marks.argmax())
print("the top mark   :", marks.max())
print("same, via index:", marks[marks.argmax()])

# argmax is still the more useful of the two when you need to know WHICH
# row or student it was - just remember to index back into the array.

---
# Part C — Write the Code  *(12 min)*

Remember: **no loops.**

---
# Part C — Write the Code

**Teaching note:** C3 is the one to demonstrate — per-row versus per-column broadcasting is
the distinction that carries straight into pandas.

### C1. Convert temperatures
The array below is in Celsius. Without a loop, produce Fahrenheit using
`F = C * 9/5 + 32`, then print how many days were above 30°C.

In [ ]:
celsius = np.array([18., 25., 31., 29., 35., 22., 27.])

# your code here

In [ ]:
celsius = np.array([18., 25., 31., 29., 35., 22., 27.])

fahrenheit = celsius * 9/5 + 32
print("fahrenheit:", fahrenheit)
print("above 30C :", (celsius > 30).sum())
print("which days:", np.where(celsius > 30)[0])

# fahrenheit: [64.4 77.  87.8 84.2 95.  71.6 80.6]
# above 30C : 2
#
# Both the * and the + broadcast a single number across all seven values.
# np.where with ONE argument returns the POSITIONS where the condition is True.

### C2. Scale to 0–1
Scale the whole array below so the smallest value becomes 0 and the largest becomes 1.
Then prove it worked.

In [ ]:
values = np.array([10., 20., 30., 40., 50.])

# your code here

In [ ]:
values = np.array([10., 20., 30., 40., 50.])

scaled = (values - values.min()) / (values.max() - values.min())
print("scaled:", scaled)
print("proof :", scaled.min(), "to", scaled.max())

# scaled: [0.   0.25 0.5  0.75 1.  ]
# proof : 0.0 to 1.0
#
# min() and max() with no axis return single numbers, which broadcast
# across the whole array.

### C3. Subtract the right average
For the marks below (3 students × 3 subjects), produce two arrays:
1. each mark minus its **student's** average
2. each mark minus its **subject's** average

Check your shapes carefully.

In [ ]:
marks = np.array([[88., 71., 64.],
                  [45., 38., 52.],
                  [91., 84., 79.]])

# your code here

In [ ]:
marks = np.array([[88., 71., 64.],
                  [45., 38., 52.],
                  [91., 84., 79.]])

student_avg = marks.mean(axis=1)      # (3,) one per ROW
subject_avg = marks.mean(axis=0)      # (3,) one per COLUMN

# Per SUBJECT: a (3,) already lines up with the last axis (the columns)
per_subject = marks - subject_avg

# Per STUDENT: must become a COLUMN first, so it lines up with the rows
per_student = marks - student_avg.reshape(-1, 1)

print("per subject:\n", per_subject.round(1))
print("\nper student:\n", per_student.round(1))

# THE KEY DIFFERENCE:
#   subject_avg is (3,) -> aligns with the COLUMNS automatically
#   student_avg is (3,) -> must be reshaped to (3,1) to align with the ROWS
#
# Each row of per_student now sums to 0; each column of per_subject does.
print("\nper_student row sums :", per_student.sum(axis=1).round(10))
print("per_subject col sums :", per_subject.sum(axis=0).round(10))

### C4. Label and count
For the marks below, without a loop:
1. produce an array of `"A"` (≥80), `"B"` (≥60), `"C"` (below 60)
2. count how many got each grade

In [ ]:
marks = np.array([88, 35, 71, 22, 64, 95, 41, 58])

# your code here

In [ ]:
marks = np.array([88, 35, 71, 22, 64, 95, 41, 58])

# np.where can be nested, just like a nested conditional expression
grades = np.where(marks >= 80, "A",
         np.where(marks >= 60, "B", "C"))

print("grades:", grades)
print("A:", (grades == "A").sum())
print("B:", (grades == "B").sum())
print("C:", (grades == "C").sum())

# grades: ['A' 'C' 'B' 'C' 'B' 'A' 'C' 'C']
# A: 2   B: 2   C: 4
#
# The nesting reads exactly like Day 2's if/elif/else, and like that chain
# the ORDER matters - test >= 80 before >= 60, or every A becomes a B.

# np.unique does the counting in one call:
labels, counts = np.unique(grades, return_counts=True)
print("\nin one call:", dict(zip(labels, counts)))

### C5. Standardise each column
Standardise the array below so every **column** has mean 0 and standard deviation 1,
then prove it.

In [ ]:
data = np.array([[10., 200., 3000.],
                 [20., 400., 1000.],
                 [30., 600., 2000.]])

# your code here

In [ ]:
data = np.array([[10., 200., 3000.],
                 [20., 400., 1000.],
                 [30., 600., 2000.]])

z = (data - data.mean(axis=0)) / data.std(axis=0)

print("standardised:\n", z.round(3))
print("\ncolumn means:", z.mean(axis=0).round(10))
print("column stds :", z.std(axis=0).round(10))

# [[-1.225 -1.225  1.225]
#  [ 0.     0.    -1.225]
#  [ 1.225  1.225  0.   ]]
# column means: [0. 0. 0.]
# column stds : [1. 1. 1.]
#
# mean(axis=0) and std(axis=0) are both (3,), which align with the columns
# automatically - no reshape needed here.
#
# This is exactly what sklearn's StandardScaler does in Module 3.

---
# Part D — Challenge  *(3 min, or take home)*

---
# Part D — Challenge

**Teaching note:** D2 is the one to show if there is time — a distance matrix from two
reshapes is the moment broadcasting stops feeling like a rule and starts feeling like a tool.

### D1. Weighted final grades
Each subject carries a different weight. Compute every student's weighted final mark
without a loop, then label each as pass (≥50) or fail.

In [ ]:
marks   = np.array([[88., 71., 64.],
                    [45., 38., 52.],
                    [91., 84., 79.],
                    [30., 41., 35.]])
weights = np.array([0.5, 0.3, 0.2])       # must sum to 1

# your code here

In [ ]:
marks   = np.array([[88., 71., 64.],
                    [45., 38., 52.],
                    [91., 84., 79.],
                    [30., 41., 35.]])
weights = np.array([0.5, 0.3, 0.2])

# Option 1 - broadcast then sum across the columns
final = (marks * weights).sum(axis=1)

# Option 2 - the same thing as a matrix-vector product
final_dot = marks @ weights

print("weighted final:", final.round(2))
print("via @         :", final_dot.round(2))
print("identical     :", np.allclose(final, final_dot))
print()
print("result:", np.where(final >= 50, "pass", "fail"))

# weighted final: [78.1 44.3 86.5 34.3]
# result: ['pass' 'fail' 'pass' 'fail']
#
# marks is (4,3) and weights is (3,) - the (3,) aligns with the COLUMNS,
# so each subject gets its own weight. Then sum(axis=1) collapses the
# subjects, leaving one number per student.
#
# marks @ weights does multiply-then-sum in a single step, which is why
# the dot product turns up everywhere in machine learning.

### D2. A distance matrix
Given the 1-D points below, build a table where entry `[i, j]` is the absolute distance
between point `i` and point `j`. No loops.

*(Hint: what shape do you need on each side?)*

In [ ]:
points = np.array([1., 4., 9., 16.])

# your code here

In [ ]:
points = np.array([1., 4., 9., 16.])

# Make one a COLUMN and leave the other a ROW, then let broadcasting
# build every pair for you.
dist = np.abs(points[:, None] - points)

print("points[:, None].shape :", points[:, None].shape)   # (4, 1)
print("points.shape          :", points.shape)            # (4,)
print("result shape          :", dist.shape)              # (4, 4)
print()
print(dist)

# [[ 0.  3.  8. 15.]
#  [ 3.  0.  5. 12.]
#  [ 8.  5.  0.  7.]
#  [15. 12.  7.  0.]]
#
# HOW IT WORKS:
#   (4, 1)  a column of points
#      (4,) a row of points
#   ------
#   (4, 4)  every pair, computed at once
#
# The diagonal is zero (each point against itself) and the table is
# symmetric, which is a free correctness check.
print("\ndiagonal all zero:", np.allclose(np.diag(dist), 0))
print("symmetric        :", np.allclose(dist, dist.T))

# This exact pattern is how K-Nearest Neighbors computes distances in
# Module 3, and how clustering algorithms build their distance matrices.

---
## Done? Self-check

- [ ] I can say which shapes will broadcast **before** running the code
- [ ] I can read a broadcast error and tell which axis clashed
- [ ] I know why a `(3,)` aligns with columns, not rows
- [ ] I can turn a `(3,)` into a column with `reshape(-1, 1)`
- [ ] I know which axis disappears when I aggregate
- [ ] I know `argmax` gives a position and `std` defaults to `ddof=0`
- [ ] I used no loops in this notebook

### Homework
1. Standardise a 10×4 random array and prove each column has mean 0.
2. Build a 10×10 multiplication table with broadcasting and no loops.
3. Write down three shape pairs that will **not** broadcast, and why.

### Next class — Topic 1.13: NumPy statistical functions
`mean`, `median`, `percentile`, correlation — and handling missing values with the
nan-aware functions.

---
*Slides & notebooks by Srinivasa Sai Chava · Boston University*

---
## Wrap-up — running the last 5 minutes

Three cold-call questions:

1. *"`(3,4)` and `(3,)` — do they broadcast?"* → No. Align right: 4 against 3.
2. *"How do I make a `(3,)` line up with the rows?"* → `reshape(-1, 1)`.
3. *"`m.sum(axis=0)` on a `(2,3)` — what shape comes out?"* → `(3,)`. The named axis goes.

**Common misconceptions to watch for today**

| Misconception | Correction |
|---|---|
| "Shapes must match exactly" | They must be **compatible** — equal, or one of them 1 |
| "Align the shapes from the left" | From the **right**. Padding happens on the left |
| "Broadcasting copies the small array" | It re-reads it. Memory cost is zero |
| "A `(3,)` lines up with the rows" | With the **last** axis — the columns |
| "`a * b` is the dot product" | That is `a @ b` |
| "`argmax` returns the largest value" | It returns its **position** |
| "`std()` is the sample std" | It is the population std. Use `ddof=1` |

**The most valuable habit from today** is the three-step debug: print both shapes, align
them from the right, ask which should be stretched. It resolves nearly every shape error
they will meet in NumPy, pandas and scikit-learn.

**Watch for students still writing loops.** The no-loops rule for this practice session is
what converts the knowledge into instinct. When you see `for i in range(len(arr))`, ask what
the whole-array version would be.

**Homework given:** standardise a 10×4 array; 10×10 table by broadcasting; three
non-broadcasting shape pairs.

**Next session:** Topic 1.13 — NumPy statistical functions. It leans directly on today's
axis rule, and adds the `nan`-aware variants, which is the first real encounter with missing
data before pandas makes it a daily concern.